tasks:
  - name: Install Julia
    init: |
      curl -fsSL https://install.julialang.org | sh
      echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
    command: echo "Julia installed"

vscode:
  extensions:
    - julialang.language-julia

ports:
  - port: 1234
    onOpen: open-preview